### ISSUE TITLE
Seek using gui not fully works

### ISSUE THREAD

**Issue by Ilya87** [andrew-bibb/mbmp#2]
Seek for videos works only using drag and drop seek slider, but not on timeline (seekbar) click.

**Comment by andrew-bibb** [comment]
I've been going back and forth on whether or not I was going to announce/release this.  Wasn't entirely sure the world needed yet another media player, but if you found it and have tried it out maybe it does.  Thank you for looking and reporting the issues.

The keyboard control does work on seeking forward and backward, and that is what I've been mostly using.  I have however also noticed the seekbar click not working, thing is I'm pretty sure it did work at one point.  Need to find what I did that broke it and undo it.  A year ago I started receiving a ton of feature requests and bug reports on CMST so I put this aside to work on those.  I've only been pecking at this on and off since, and a bit more lately.  As I mentioned on the CMST thread for the next couple of months I'm mainly going to be enjoying the outdoors, although I did a bit of coding on this today because it is cold, rainy, and close to snowing.  I'm also planning to use this program as a test bed for the custom icon feature request on CMST.  I'll play with it here and when it works port it over to CMST.

Thank you again for going looking this over, and I will put the issues on the front burner to fix.

**Comment by Ilya87** [comment]
First, thank you very much for CMST - it's the only one network manager, written for Qt 5 without DE dependencies, which makes it ideal for LXQt and other Qt 5 based DE.
Second, continue please to work on this player to make it lightweight by design. Now we have Qt 5 ffmpeg-based bomi, mplayer-based smplayer and gstreamer-based mbmp. So, it is possible to make your project competitive.

**Comment by andrew-bibb** [comment]
I'll continue to work on this.  I was going to anyway just for myself, but now that I know at least one other person is interested I'll work for a formal release and announcement.

I figured out where I broke the slider bar, and indeed it was me.  Happened when I was trying to sync the slider (and time display) with the stream position.  Implemented it in that direction but broke it going the other way, which had been working.  Once I know what a problem is I can usually fix it so I should be able to fix this issue.

**Comment by andrew-bibb** [comment]
The current version in git should have fixed this.  I've also updated the packaged release to include it (version 2015.06.02).  Still working on adding the option to restore the playing media if the player is closed while something is playing.

**Comment by Ilya87** [comment]
Not fixed. Now mbmp goes to only 12 minutes (in my test video) to cursor position, so I need to click not once on the seekbar to reach target cursor position.

**Comment by andrew-bibb** [comment]
Clicking on the bar jumps a page step which will vary depending on the length of the video (one page is 1/10 of the stream duration).  It actually is working the way I intended, but I see where you are trying to go with it and I should be able to implement that. I've reopened the issue.

**Comment by andrew-bibb** [comment]
I think this is what you were getting at.  The slider will now jump to the mouse position on a left click.  Right click still opens up the context menu.
