### ISSUE TITLE
Implement floating point audio decoding 

### ISSUE THREAD

**Issue by Ilya87** [andrew-bibb/mbmp#3]
Until bug https://bugzilla.gnome.org/show_bug.cgi?id=746330 will be solved, audio stream should be decoded using floating point audio decoding.

**Comment by andrew-bibb** [comment]
Wanted to let you know that I've looked at this issue a bit, but my current impression is that there is not much I can do.  We use the GStreamer playbin element mainly because it automatically creates the pipeline based on media type and the users computer.  With playbin I can change the utlimate sink, but I'm pretty sure I can't change an intermediate element, for instance the decoder.  

I'm going to leave this open for now as I'm still looking, but at the moment I'm stuck.

**Comment by andrew-bibb** [comment]
Update: it appears that there is a way to assign ranks to various GStreamer elements, so that one will be selected over another.  

I'm going to look into implementing this.

**Comment by Ilya87** [comment]
In my opinion to solve this issue implementing floating point decoder should be enough only for mp3 codec.

**Comment by andrew-bibb** [comment]
I just uploaded an attempt to raise the ranking of GStreamer element `avdec_mp3float`.  Raising the ranking should allow it to be selected over any other element that could be used, for instance the integer version.

If you start from a command line you will see some debug output printed.  This is very ratty at the moment and more proof of concept.  I'm actually not sure it is working as I can play mp3's just fine using either decoder.

**Comment by Ilya87** [comment]
I think it's fixed now. Thank you.

**Comment by andrew-bibb** [comment]
Fantastic.

Now that I know that code block works I'm going to clean things up and make it so users can blacklist or promote any GStreamer element they want.  

Thanks for reporting the issue and checking it.
